use master;
GO
CREATE DATABASE [flask-database];
GO
USE [flask-database];
GO
CREATE LOGIN YAKOV WITH PASSWORD = "Passw0rd!";
GO
CREATE USER YAKOV FOR LOGIN YAKOV;
GO
GRANT CREATE TABLE TO YAKOV;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA :: dbo TO YAKOV;
GO
GRANT CONTROL ON SCHEMA :: dbo TO YAKOV;